import os
import hashlib
import logging
from datetime import datetime
import xml.etree.ElementTree as ET

import requests

from domain.job import Job

log = logging.getLogger(__name__)

SCRAPERAPI_KEY = os.getenv("SCRAPERAPI_KEY")

SEARCH_QUERIES = [
    {"q": "看護師", "l": "東京"},
    {"q": "医師", "l": "東京"},
    {"q": "薬剤師", "l": "東京"},
]


def fetch_url(url: str, use_proxy: bool = False) -> requests.Response:
    """Fetch URL directly or via ScraperAPI."""
    if use_proxy and SCRAPERAPI_KEY:
        log.info(f"[INDEED] Using ScraperAPI for: {url}")
        return requests.get(
            "http://api.scraperapi.com",
            params={
                "api_key": SCRAPERAPI_KEY,
                "url": url,
                "country_code": "jp",
                "render": "false",  # keep render=false to save requests
            },
            timeout=30,
        )

    log.info(f"[INDEED] Direct fetch: {url}")
    return requests.get(
        url,
        headers={"User-Agent": "Mozilla/5.0 (compatible; RSS reader)"},
        timeout=30,
    )


def _dict_jobs_to_domain_jobs(job_dicts: list[dict]) -> list[Job]:
    """Convert the job dictionaries into our internal `domain.job.Job` objects."""
    jobs: list[Job] = []
    for jd in job_dicts:
        job = Job(
            source=str(jd.get("source", "") or ""),
            mode="scraperapi_with_rss_fallback",
            raw_facility=str(jd.get("raw_facility", "") or ""),
            job_title=str(jd.get("job_title", "") or ""),
            location=str(jd.get("location", "") or ""),
            job_description=str(jd.get("job_description", "") or ""),
            requirements=str(jd.get("requirements", "") or ""),
            salary_raw=str(jd.get("salary_raw", "") or ""),
            employment_type=str(jd.get("employment_type", "") or ""),
            application_deadline=str(jd.get("application_deadline", "") or ""),
            contact_information=str(jd.get("contact_information", "") or ""),
            url=str(jd.get("url", "") or ""),
        )
        # Preserve the deterministic id/scraped_at generated by the scraper.
        job.id = str(jd.get("id", job.id))
        scraped_at = jd.get("scraped_at") or None
        if scraped_at:
            job.scraped_at = str(scraped_at)
        jobs.append(job)
    return jobs


def scrape_indeed_rss(query: str, location: str) -> list[Job]:
    """Try RSS feed first — free, no proxy needed."""
    rss_url = f"https://jp.indeed.com/rss?q={query}&l={location}&limit=50"

    try:
        response = fetch_url(rss_url, use_proxy=False)
        if response.status_code == 200 and "<rss" in response.text:
            return _dict_jobs_to_domain_jobs(parse_rss(response.text, query, location))
        log.warning(f"[INDEED] RSS blocked for {query}/{location} — trying ScraperAPI")
    except Exception as e:
        log.warning(f"[INDEED] RSS failed: {e}")

    # Fallback to ScraperAPI
    try:
        search_url = f"https://jp.indeed.com/jobs?q={query}&l={location}&limit=50"
        response = fetch_url(search_url, use_proxy=True)
        if response.status_code == 200:
            return _dict_jobs_to_domain_jobs(parse_html(response.text, query, location))
        log.error(f"[INDEED] ScraperAPI also failed: {response.status_code}")
    except Exception as e:
        log.error(f"[INDEED] ScraperAPI failed: {e}")

    return []


def parse_rss(xml_text: str, query: str, location: str) -> list[dict]:
    """Parse Indeed RSS feed into standard job schema."""
    jobs: list[dict] = []
    try:
        root = ET.fromstring(xml_text)
        for item in root.findall(".//item"):
            title = item.find("title")
            link = item.find("link")
            description = item.find("description")

            if not title or not link:
                continue

            job_id = hashlib.md5(f"indeed_japan|{title.text}|{location}".encode()).hexdigest()

            jobs.append(
                {
                    "id": job_id,
                    "source": "indeed_japan",
                    "raw_facility": extract_facility(title.text or ""),
                    "masked_facility": "",
                    "job_title": clean_title(title.text or ""),
                    "location": location,
                    "job_description": strip_html(description.text if description is not None else ""),
                    "requirements": "",
                    "salary_raw": extract_salary(description.text if description is not None else ""),
                    "salary_masked": "",
                    "employment_type": "",
                    "application_deadline": "",
                    "contact_information": "",
                    "url": link.text or "",
                    "scraped_at": datetime.utcnow().isoformat(),
                }
            )
    except ET.ParseError as e:
        log.error(f"[INDEED] RSS parse error: {e}")

    log.info(f"[INDEED] RSS parsed {len(jobs)} jobs for {query}/{location}")
    return jobs


def parse_html(html: str, query: str, location: str) -> list[dict]:
    """Parse Indeed HTML search results via BeautifulSoup."""
    from bs4 import BeautifulSoup

    jobs: list[dict] = []

    try:
        soup = BeautifulSoup(html, "html.parser")
        job_cards = soup.find_all("div", class_="job_seen_beacon")

        for card in job_cards:
            title_el = card.find("span", {"data-testid": "jobTitle"}) or card.find("h2")
            company_el = card.find("span", {"data-testid": "company-name"})
            location_el = card.find("div", {"data-testid": "text-location"})
            salary_el = card.find("div", {"data-testid": "attribute_snippet_testid"})
            link_el = card.find("a", href=True)

            if not title_el:
                continue

            job_id = hashlib.md5(f"indeed_japan|{title_el.text}|{location}".encode()).hexdigest()

            jobs.append(
                {
                    "id": job_id,
                    "source": "indeed_japan",
                    "raw_facility": company_el.text.strip() if company_el else "",
                    "masked_facility": "",
                    "job_title": title_el.text.strip(),
                    "location": location_el.text.strip() if location_el else location,
                    "job_description": "",
                    "requirements": "",
                    "salary_raw": salary_el.text.strip() if salary_el else "",
                    "salary_masked": "",
                    "employment_type": "",
                    "application_deadline": "",
                    "contact_information": "",
                    "url": f"https://jp.indeed.com{link_el['href']}" if link_el else "",
                    "scraped_at": datetime.utcnow().isoformat(),
                }
            )
    except Exception as e:
        log.error(f"[INDEED] HTML parse error: {e}")

    log.info(f"[INDEED] HTML parsed {len(jobs)} jobs")
    return jobs


def clean_title(raw: str) -> str:
    if " - " in raw:
        return raw.split(" - ")[0].strip()
    return raw.strip()


def extract_facility(raw: str) -> str:
    if " - " in raw:
        parts = raw.split(" - ")
        return parts[1].strip() if len(parts) > 1 else ""
    return ""


def extract_salary(description: str) -> str:
    import re

    if not description:
        return ""
    match = re.search(r"[\d,]+\s*円", description)
    return match.group(0) if match else ""


def strip_html(html: str) -> str:
    import re

    return re.sub(r"<[^>]+>", "", html).strip()


async def run() -> list[Job]:
    """Main entry point called by pipeline."""
    all_jobs: list[Job] = []
    for query_config in SEARCH_QUERIES:
        jobs = scrape_indeed_rss(query=query_config["q"], location=query_config["l"])
        all_jobs.extend(jobs)
        log.info(f"[INDEED] Total so far: {len(all_jobs)}")
    return all_jobs

